In [7]:
import pandas as pd
import numpy as np
from datetime import timedelta

In [11]:
symptoms = pd.read_pickle('processed_symptoms.pkl')
symptoms.describe()

,user_id,acne,backache,bloating,cramp,diarrhea,dizzy,headache,mood,nausea,sore,cycle_length_initial,period_length_initial,cycle_percentage
count,16917.000000,16917.000000,16917.000000,16917.000000,16917.000000,16917.000000,16917.000000,16917.000000,16917.000000,16917.000000,16917.000000,16917,16917,16917.000000
mean,3522.971567,10.804753,17.293255,18.469764,24.758704,6.510315,5.883667,14.976651,19.936218,6.607200,14.651830,28 days 15:55:08.884553,5 days 14:46:22.195424,0.430031
std,1869.271500,21.203897,28.427643,28.945317,32.859893,18.070838,17.095204,26.790871,31.260061,18.696963,27.330372,2 days 17:08:38.143691,2 days 03:09:37.301652,0.353506
min,252.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,25 days 00:00:00,2 days 00:00:00,0.025000
25%,2025.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,28 days 00:00:00,5 days 00:00:00,0.103448
50%,3375.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,28 days 00:00:00,5 days 00:00:00,0.285714
75%,5045.000000,14.000000,30.000000,33.000000,46.000000,0.000000,0.000000,23.000000,35.000000,0.000000,20.000000,29 days 00:00:00,7 days 00:00:00,0.821429
max,7054.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,40 days 00:00:00,35 days 00:00:00,1.000000

In [10]:
symptoms[symptoms.cycle_length_initial == timedelta(days=28)]

(9654, 20)

In [20]:
d = {}
for cl in range(25, 40):
    for pl in range(2,7):
        d["{}_{}".format(cl, pl)] = 0
        

        
for cl in range(25, 40):
    for pl in range(2,7):
        cld = timedelta(days=cl)
        pld = timedelta(days=pl)
        ll = symptoms[(symptoms.cycle_length_initial == cld) & ( symptoms.period_length_initial == pld )].shape[0]
        d["{}_{}".format(cl, pl)] = ll

In [22]:
def get_distribution(pl, cl):
    
    pass

SyntaxError: unexpected EOF while parsing (<ipython-input-22-57e2b06a7091>, line 1)